export interface StratumLocation {
  id: string;
  name: string;
  nameLocal?: string;
  lat: number;
  lng: number;
  country: string;
  region: string;
  category: 'friction_zone' | 'religious_center' | 'asabiyyah_node' | 'trauma_site' | 'cognitive_warfare_hub';
  primaryLens: 'identity_sacred' | 'demographic' | 'humiliation' | 'religious_networks' | 'civilizational' | 'cognitive_warfare';
  intensity: 1 | 2 | 3 | 4 | 5;
  description: string;
  historicalEvents?: string[];
  activeSince?: string;
  predictedPhase?: string;
  sources?: string[];
}

export const FRICTION_ZONES: StratumLocation[] = [
  {
    id: 'friction_001',
    name: 'Jerusalem / Al-Quds',
    nameLocal: 'ירושלים / القدس',
    lat: 31.7683,
    lng: 35.2137,
    country: 'Israel/Palestine',
    region: 'Middle East',
    category: 'friction_zone',
    primaryLens: 'identity_sacred',
    intensity: 5,
    description: 'Epicenter of friction between Judaism, Christianity, and Islam',
    historicalEvents: ['Temple Destruction 70 CE', 'Crusades 1099', 'Six-Day War 1967'],
    activeSince: '1000 BCE',
    predictedPhase: 'Religious Energy Cycle: Political Reactivation',
  },
  {
    id: 'friction_002',
    name: 'Kashmir',
    lat: 34.0836,
    lng: 74.7973,
    country: 'India/Pakistan',
    region: 'South Asia',
    category: 'friction_zone',
    primaryLens: 'civilizational',
    intensity: 4,
    description: 'Friction between Hindu and Islamic civilizations since Partition',
    activeSince: '1947',
    predictedPhase: 'Demographic Cycle: Expansion',
  },
  {
    id: 'friction_003',
    name: 'Xinjiang (Urumqi)',
    lat: 43.8256,
    lng: 87.6168,
    country: 'China',
    region: 'Central Asia',
    category: 'friction_zone',
    primaryLens: 'identity_sacred',
    intensity: 5,
    description: 'Secular-authoritarian state vs Uyghur Muslim identity',
    activeSince: '2009',
    predictedPhase: 'Cognitive Warfare: Industrial-scale narrative control',
  },
  {
    id: 'friction_004',
    name: 'Ayodhya',
    lat: 26.7922,
    lng: 82.1998,
    country: 'India',
    region: 'South Asia',
    category: 'friction_zone',
    primaryLens: 'identity_sacred',
    intensity: 4,
    description: 'Site of Babri Mosque destruction, Ram Temple construction',
    activeSince: '1992',
    predictedPhase: 'Religious Energy: Institutionalization (BJP in power)',
  },
  {
    id: 'friction_005',
    name: 'Mexico City',
    nameLocal: 'Ciudad de México',
    lat: 19.4326,
    lng: -99.1332,
    country: 'Mexico',
    region: 'Mexico',
    category: 'friction_zone',
    primaryLens: 'identity_sacred',
    intensity: 4,
    description: 'Messianic political polarization. AMLO legacy vs institutional democracy.',
    activeSince: '2018',
    predictedPhase: 'escalation',
    historicalEvents: ['Mexican Revolution 1910', 'AMLO presidency 2018'],
  },
  {
    id: 'friction_006',
    name: 'Jerusalem',
    nameLocal: 'ירושלים',
    lat: 31.7683,
    lng: 35.2137,
    country: 'Israel',
    region: 'Israel',
    category: 'friction_zone',
    primaryLens: 'religious_networks',
    intensity: 5,
    description: 'Secular-haredi fracture. Nation-state vs tribe-people definition conflict.',
    activeSince: '2023',
    predictedPhase: 'critical',
    historicalEvents: ['Judicial reform crisis 2023', 'Haredi draft exemption controversy'],
  },
  {
    id: 'friction_007',
    name: 'Ayodhya',
    nameLocal: 'अयोध्या',
    lat: 26.7922,
    lng: 82.1998,
    country: 'India',
    region: 'India',
    category: 'friction_zone',
    primaryLens: 'identity_sacred',
    intensity: 5,
    description: 'Hindu nationalist restoration project. Sacred site reclamation as civilizational policy.',
    activeSince: '2019',
    predictedPhase: 'critical',
    historicalEvents: ['Ram Temple construction 2020-2024', 'Consecration January 2024'],
  },
  {
    id: 'friction_008',
    name: 'Jalisco',
    nameLocal: 'Jalisco',
    lat: 20.6597,
    lng: -103.3496,
    country: 'Mexico',
    region: 'Mexico',
    category: 'friction_zone',
    primaryLens: 'religious_networks',
    intensity: 4,
    description: 'Guadalajara: Center of conservative Mexican Catholicism. Tension between traditional hierarchy and charismatic evangelical expansion.',
    activeSince: '2008',
    predictedPhase: 'Religious Energy: Conservative Institutionalization',
    historicalEvents: ['Cristero War 1926-1929', 'Rise of Evangelical Churches 2000+', 'Catholic vs Charismatic tensions 2010+'],
  },
  {
    id: 'friction_009',
    name: 'Michoacán',
    nameLocal: 'Michoacán',
    lat: 19.5881,
    lng: -101.5270,
    country: 'Mexico',
    region: 'Mexico',
    category: 'friction_zone',
    primaryLens: 'humiliation',
    intensity: 5,
    description: 'Tierra Caliente: Criminal cartels as parallel state power. Systematic humiliation of institutional authority by drug trafficking organizations.',
    activeSince: '2006',
    predictedPhase: 'Humiliation Cycle: State Legitimacy Collapse',
    historicalEvents: ['War on Drugs 2006', 'La Tuta Regime (Knights Templar)', 'CJNG Expansion 2014+', 'Massacres and Mass Graves'],
  },
  {
    id: 'friction_010',
    name: 'Baja California',
    nameLocal: 'Baja California',
    lat: 32.5149,
    lng: -116.9718,
    country: 'Mexico',
    region: 'Mexico',
    category: 'friction_zone',
    primaryLens: 'civilizational',
    intensity: 4,
    description: 'US-Mexico border. Civilizational friction point: Anglo-American vs Hispanic-Catholic cultures, migration pressures, economic asymmetry.',
    activeSince: '1848',
    predictedPhase: 'Civilizational Friction: Border Reactivation (post-2016)',
    historicalEvents: ['Treaty of Guadalupe Hidalgo 1848', 'NAFTA 1994', 'Trump Border Policy 2016', 'Migration Crisis 2018+'],
  },
  {
    id: 'friction_011',
    name: 'Quintana Roo',
    nameLocal: 'Quintana Roo (Tulum)',
    lat: 20.2114,
    lng: -87.4240,
    country: 'Mexico',
    region: 'Mexico',
    category: 'friction_zone',
    primaryLens: 'cognitive_warfare',
    intensity: 3,
    description: 'Tulum: Hub of mystical movements, New Age networks, and transformational tourism. Cognitive warfare through alternative narratives and consciousness manipulation.',
    activeSince: '2000',
    predictedPhase: 'Cognitive Warfare: Mystical Narrative Expansion',
    historicalEvents: ['Tulum Tourism Boom 2000+', 'New Age Movement Expansion 2010+', 'Ayahuasca Retreat Culture'],
  },
  {
    id: 'friction_012',
    name: 'Delhi',
    nameLocal: 'दिल्ली',
    lat: 28.7041,
    lng: 77.1025,
    country: 'India',
    region: 'India',
    category: 'friction_zone',
    primaryLens: 'cognitive_warfare',
    intensity: 4,
    description: 'Capital politique, centralized Hindu nationalist narrative. Center of institutional narrative control and media manipulation.',
    activeSince: '2014',
    predictedPhase: 'Cognitive Warfare: Institutional Narrative Control',
    historicalEvents: ['Modi Presidency 2014', 'Hindu Nationalism Ascendancy', 'Media Control Expansion'],
  },
  {
    id: 'friction_013',
    name: 'Mumbai',
    nameLocal: 'मुंबई',
    lat: 19.0760,
    lng: 72.8777,
    country: 'India',
    region: 'India',
    category: 'friction_zone',
    primaryLens: 'demographic',
    intensity: 4,
    description: 'Megacity of 20M: Hindu-Muslim tension, historical riots, segregated neighborhoods, demographic pressure.',
    activeSince: '1992',
    predictedPhase: 'Demographic Cycle: Religious Segregation',
    historicalEvents: ['Mumbai Riots 1992-93', 'Babri Mosque Destruction', 'Hindu-Muslim Tensions', '26/11 Attacks 2008'],
  },
  {
    id: 'friction_014',
    name: 'Varanasi',
    nameLocal: 'वाराणसी',
    lat: 25.3200,
    lng: 82.9850,
    country: 'India',
    region: 'India',
    category: 'friction_zone',
    primaryLens: 'identity_sacred',
    intensity: 5,
    description: 'Holiest Hindu city. Modi political constituency. Temple development as civilizational policy. Sacred site weaponized.',
    activeSince: '1000 BCE',
    predictedPhase: 'Religious Energy: Political Sacralization',
    historicalEvents: ['Sacred Ganges Pilgrimage Site', 'Modi Constituency Connection', 'Temple Development Projects'],
  },
  {
    id: 'friction_015',
    name: 'Ujjain',
    nameLocal: 'उज्जैन',
    lat: 23.1815,
    lng: 75.7733,
    country: 'India',
    region: 'India',
    category: 'friction_zone',
    primaryLens: 'religious_networks',
    intensity: 4,
    description: 'Mahakaleshwar Temple hub. Center of massive pilgrimage networks. Kumbh Mela host. Religious authority redistribution.',
    activeSince: '1000 BCE',
    predictedPhase: 'Religious Energy: Pilgrimage Network Expansion',
    historicalEvents: ['Mahakaleshwar Temple', 'Kumbh Mela Gatherings', 'Hindu Pilgrimage Networks'],
  },
  {
    id: 'friction_016',
    name: 'Rishikesh',
    nameLocal: 'ऋषिकेश',
    lat: 30.0891,
    lng: 78.2679,
    country: 'India',
    region: 'India',
    category: 'friction_zone',
    primaryLens: 'civilizational',
    intensity: 3,
    description: 'Yoga capital. Global export of Hinduism and Hindu spirituality. Western adoption of Hindu practices, ashram tourism.',
    activeSince: '1960',
    predictedPhase: 'Civilizational Export: Hindu Spirituality Globalization',
    historicalEvents: ['The Beatles Visit 1968', 'Yoga Capital Status', 'Ashram Tourism Expansion', 'Western Hindu Practice Adoption'],
  },
  {
    id: 'friction_017',
    name: 'Tel Aviv',
    nameLocal: 'תל אביב',
    lat: 32.0853,
    lng: 34.7818,
    country: 'Israel',
    region: 'Israel',
    category: 'friction_zone',
    primaryLens: 'humiliation',
    intensity: 4,
    description: 'Secular liberal enclave. Mass protests against judicial reform. Internal schism between secular and religious Jews.',
    activeSince: '2023',
    predictedPhase: 'Humiliation Cycle: Internal Legitimacy Crisis',
    historicalEvents: ['Judicial Reform Crisis 2023', 'Mass Secular Protests (500K+)', 'Ben-Gvir Police Control', 'Secular-Religious Schism'],
  },
  {
    id: 'friction_018',
    name: 'Eilat',
    nameLocal: 'אילת',
    lat: 29.5581,
    lng: 34.9499,
    country: 'Israel',
    region: 'Israel',
    category: 'friction_zone',
    primaryLens: 'civilizational',
    intensity: 3,
    description: 'Southern border gateway. Corridor to Saudi Arabia. Abraham Accords symbolic point. Israel-Arab civilization diplomacy.',
    activeSince: '2020',
    predictedPhase: 'Civilizational Diplomacy: Abraham Accords Realization',
    historicalEvents: ['Abraham Accords 2020', 'Israel-UAE Normalization', 'Saudi Corridor Opening', 'Sunni-Zionist Alliance'],
  },
  {
    id: 'friction_019',
    name: 'Haifa',
    nameLocal: 'חיפה',
    lat: 32.8191,
    lng: 34.9885,
    country: 'Israel',
    region: 'Israel',
    category: 'friction_zone',
    primaryLens: 'demographic',
    intensity: 3,
    description: 'Arab-Jewish coexistence model under pressure. Mixed city tensions rising. Oct 7 2023 fractured internal dynamics.',
    activeSince: '1948',
    predictedPhase: 'Demographic Coexistence: Under Critical Strain',
    historicalEvents: ['Israeli Independence 1948', 'Arab-Jewish Coexistence Tradition', 'Oct 7 Tensions 2023'],
  },
  {
    id: 'friction_020',
    name: 'Monte Hermón',
    nameLocal: 'הר חרמון',
    lat: 33.4166,
    lng: 35.7833,
    country: 'Israel',
    region: 'Israel',
    category: 'friction_zone',
    primaryLens: 'cognitive_warfare',
    intensity: 4,
    description: 'Northern border with Syria/Lebanon. Hezbollah surveillance. Psychological warfare zone. Intelligence operations hub.',
    activeSince: '1967',
    predictedPhase: 'Cognitive Warfare: Northern Border Surveillance (Active)',
    historicalEvents: ['Six-Day War 1967 capture', 'Yom Kippur War 1973', 'Hezbollah Border Operations', 'Psychological Warfare Intensity'],
  },
];

export const RELIGIOUS_POWER_CENTERS: StratumLocation[] = [
  {
    id: 'religious_001',
    name: 'Vatican City',
    lat: 41.9029,
    lng: 12.4534,
    country: 'Vatican City',
    region: 'Europe',
    category: 'religious_center',
    primaryLens: 'religious_networks',
    intensity: 3,
    description: 'Seat of Catholic Church, 1.3B global network',
    activeSince: '1929',
    predictedPhase: 'Religious Energy: Sclerosis phase',
  },
  {
    id: 'religious_002',
    name: 'Qom',
    lat: 34.6416,
    lng: 50.8746,
    country: 'Iran',
    region: 'Middle East',
    category: 'religious_center',
    primaryLens: 'religious_networks',
    intensity: 5,
    description: 'Center of Shia clergy, theocratic power base',
    activeSince: '1979',
    predictedPhase: 'Religious Energy: Political Reactivation sustained',
  },
  {
    id: 'religious_003',
    name: 'Mecca',
    lat: 21.4225,
    lng: 39.8262,
    country: 'Saudi Arabia',
    region: 'Middle East',
    category: 'religious_center',
    primaryLens: 'identity_sacred',
    intensity: 5,
    description: 'Epicenter of Islam, 1.8B oriented toward this point',
    activeSince: '622 CE',
    predictedPhase: 'Religious Energy: Institutionalization (state control)',
  },
];

export const ASABIYYAH_NODES: StratumLocation[] = [
  {
    id: 'asabiyyah_001',
    name: 'West Bank Settlements',
    lat: 31.9,
    lng: 35.2,
    country: 'Israel/Palestine',
    region: 'Middle East',
    category: 'asabiyyah_node',
    primaryLens: 'identity_sacred',
    intensity: 5,
    description: 'Religious settler communities with high ideological cohesion',
    activeSince: '1967',
    predictedPhase: 'Asabiyyah Cycle: Active Expansion',
  },
];

export const TRAUMA_SITES: StratumLocation[] = [
  {
    id: 'trauma_001',
    name: 'Auschwitz-Birkenau',
    lat: 50.0355,
    lng: 19.1783,
    country: 'Poland',
    region: 'Central Europe',
    category: 'trauma_site',
    primaryLens: 'humiliation',
    intensity: 5,
    description: 'Holocaust symbol, foundational trauma of Israel',
    activeSince: '1945',
    predictedPhase: 'Long-lived trauma (generational transmission)',
  },
  {
    id: 'trauma_002',
    name: 'Srebrenica',
    lat: 44.1065,
    lng: 19.2978,
    country: 'Bosnia and Herzegovina',
    region: 'Southeastern Europe',
    category: 'trauma_site',
    primaryLens: 'humiliation',
    intensity: 5,
    description: 'Genocide of 8,000 Bosnian Muslims (1995)',
    activeSince: '1995',
    predictedPhase: 'Active trauma (less than 50 years)',
  },
];

export const COGNITIVE_WARFARE_HUBS: StratumLocation[] = [
  {
    id: 'cognitive_001',
    name: 'St. Petersburg (IRA HQ)',
    lat: 59.9311,
    lng: 30.3609,
    country: 'Russia',
    region: 'Eastern Europe',
    category: 'cognitive_warfare_hub',
    primaryLens: 'cognitive_warfare',
    intensity: 5,
    description: 'Internet Research Agency headquarters',
    activeSince: '2013',
    predictedPhase: 'Cognitive Warfare Cycle: Information Weapon (active)',
  },
];

export const ALL_STRATUM_LOCATIONS: StratumLocation[] = [
  ...FRICTION_ZONES,
  ...RELIGIOUS_POWER_CENTERS,
  ...ASABIYYAH_NODES,
  ...TRAUMA_SITES,
  ...COGNITIVE_WARFARE_HUBS,
];

export function getLocationsByLens(lens: StratumLocation['primaryLens']): StratumLocation[] {
  return ALL_STRATUM_LOCATIONS.filter(loc => loc.primaryLens === lens);
}

export function getLocationsByIntensity(minIntensity: number): StratumLocation[] {
  return ALL_STRATUM_LOCATIONS.filter(loc => loc.intensity >= minIntensity);
}

export function getLocationsByCategory(category: StratumLocation['category']): StratumLocation[] {
  return ALL_STRATUM_LOCATIONS.filter(loc => loc.category === category);
}
